#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use CLI\I18nCommands;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new I18nCommands());
$application->run();
